'use strict';
/**
 * The 113 revenue villages of Leh district, by sub-division and block, from the
 * district administration's village list. Synced into the villages table on every
 * start (see syncDistrictVillages in db.js), so adding a row here is all it takes.
 */

const LEH_VILLAGES = [
  ['Leh Hqtr', 'Chuchot', 'Chuchot Yakma'],
  ['Leh Hqtr', 'Chuchot', 'Chuchot Gongma'],
  ['Leh Hqtr', 'Chuchot', 'Chuchot Shama'],
  ['Leh Hqtr', 'Chuchot', 'Mathoo'],
  ['Leh Hqtr', 'Chuchot', 'Stakna'],
  ['Leh Hqtr', 'Chuchot', 'Stok'],
  ['Nubra', 'Diskit', 'Diger'],
  ['Nubra', 'Diskit', 'Disket'],
  ['Nubra', 'Diskit', 'Hundar'],
  ['Nubra', 'Diskit', 'Hundar Dok'],
  ['Nubra', 'Diskit', 'Hundri'],
  ['Nubra', 'Diskit', 'Khalsar'],
  ['Nubra', 'Diskit', 'Khardong'],
  ['Nubra', 'Diskit', 'Khema Khungru'],
  ['Nubra', 'Diskit', 'Lakjung'],
  ['Nubra', 'Diskit', 'Largiab'],
  ['Nubra', 'Diskit', 'Partapur'],
  ['Nubra', 'Diskit', 'Skanpuk'],
  ['Nubra', 'Diskit', 'Skuru'],
  ['Nubra', 'Diskit', 'Tangyar'],
  ['Nubra', 'Diskit', 'Terchey'],
  ['Nubra', 'Diskit', 'Udmaru'],
  ['Nubra', 'Diskit', 'Warisfistan'],
  ['Durbuk', 'Durbuk', 'Chushul'],
  ['Durbuk', 'Durbuk', 'Durbuk'],
  ['Durbuk', 'Durbuk', 'Kargyam'],
  ['Durbuk', 'Durbuk', 'Man Pangong'],
  ['Durbuk', 'Durbuk', 'Shachukul'],
  ['Durbuk', 'Durbuk', 'Tangste'],
  ['Khaltsi', 'Khaltsi', 'Kanji'],
  ['Khaltsi', 'Khaltsi', 'Khaltsi'],
  ['Khaltsi', 'Khaltsi', 'Lamayuru'],
  ['Khaltsi', 'Khaltsi', 'Leh Dho'],
  ['Khaltsi', 'Khaltsi', 'Nurla'],
  ['Khaltsi', 'Khaltsi', 'Skindiang'],
  ['Khaltsi', 'Khaltsi', 'Takmachik'],
  ['Khaltsi', 'Khaltsi', 'Temisgam'],
  ['Khaltsi', 'Khaltsi', 'Tia'],
  ['Kharu', 'Kharu', 'Changa'],
  ['Kharu', 'Kharu', 'Chemday'],
  ['Kharu', 'Kharu', 'Gia'],
  ['Kharu', 'Kharu', 'Hemis'],
  ['Kharu', 'Kharu', 'Igoo'],
  ['Kharu', 'Kharu', 'Khargu'],
  ['Kharu', 'Kharu', 'Langokor'],
  ['Kharu', 'Kharu', 'Matselang'],
  ['Kharu', 'Kharu', 'Miru'],
  ['Kharu', 'Kharu', 'Phuktse'],
  ['Kharu', 'Kharu', 'Serthi'],
  ['Kharu', 'Kharu', 'Shang'],
  ['Kharu', 'Kharu', 'Shara'],
  ['Kharu', 'Kharu', 'Sharnose'],
  ['Kharu', 'Kharu', 'Upshi'],
  ['Leh Hqtr', 'Leh', 'Phey'],
  ['Leh Hqtr', 'Leh', 'Saboo'],
  ['Leh Hqtr', 'Leh', 'Phyang'],
  ['Leh Hqtr', 'Leh', 'Spituk'],
  ['Leh Hqtr', 'Leh', 'Cholglamsar'],
  ['Likir', 'Nimoo', 'Bazgoo'],
  ['Likir', 'Nimoo', 'Chiling Sumda'],
  ['Likir', 'Nimoo', 'Likir'],
  ['Likir', 'Nimoo', 'Ney'],
  ['Likir', 'Nimoo', 'Nimo'],
  ['Likir', 'Nimoo', 'Rumbak'],
  ['Likir', 'Nimoo', 'Skiumarkha'],
  ['Likir', 'Nimoo', 'Taroo'],
  ['Likir', 'Nimoo', 'Umla'],
  ['Nyoma', 'Nyoma', 'Anlay'],
  ['Nyoma', 'Nyoma', 'Demjok'],
  ['Nyoma', 'Nyoma', 'Koyul'],
  ['Nyoma', 'Nyoma', 'Mood'],
  ['Nyoma', 'Nyoma', 'Nyoma'],
  ['Nubra', 'Panamik', 'Chamshan Charasa'],
  ['Nubra', 'Panamik', 'Khemi'],
  ['Nubra', 'Panamik', 'Kubed'],
  ['Nubra', 'Panamik', 'Panamic'],
  ['Nubra', 'Panamik', 'Sumoor'],
  ['Nubra', 'Panamik', 'Tiggar'],
  ['Nyoma', 'Rong-Chumathang', 'Chumathang'],
  ['Nyoma', 'Rong-Chumathang', 'Himya'],
  ['Nyoma', 'Rong-Chumathang', 'Kerey'],
  ['Nyoma', 'Rong-Chumathang', 'Kumgyam'],
  ['Nyoma', 'Rong-Chumathang', 'Liktse'],
  ['Nyoma', 'Rong-Chumathang', 'Skitmang'],
  ['Nyoma', 'Rong-Chumathang', 'Tarchit'],
  ['Nyoma', 'Rong-Chumathang', 'Teri'],
  ['Nyoma', 'Rong-Chumathang', 'Tukla'],
  ['Nyoma', 'Rupsho-Puga', 'Karzok'],
  ['Nyoma', 'Rupsho-Puga', 'Kharnak'],
  ['Nyoma', 'Rupsho-Puga', 'Samad Rakchan'],
  ['Likir', 'Saspol', 'Alchi'],
  ['Likir', 'Saspol', 'Giramangu'],
  ['Likir', 'Saspol', 'Saspochey'],
  ['Likir', 'Saspol', 'Suspol'],
  ['Likir', 'Saspol', 'Tarhipti'],
  ['Likir', 'Saspol', 'Hemishok Pachan'],
  ['Khaltsi', 'Singaylalok', 'Fotoksar'],
  ['Khaltsi', 'Singaylalok', 'Lingshet'],
  ['Khaltsi', 'Singaylalok', 'Wanla'],
  ['Khaltsi', 'Singaylalok', 'Youl Chung'],
  ['Khaltsi', 'Skurbuchan', 'Dah'],
  ['Khaltsi', 'Skurbuchan', 'Damkhar'],
  ['Khaltsi', 'Skurbuchan', 'Hanoo'],
  ['Khaltsi', 'Skurbuchan', 'Skur Buchan'],
  ['Leh Hqtr', 'Thiksay', 'Nang'],
  ['Leh Hqtr', 'Thiksay', 'Rambir Por'],
  ['Leh Hqtr', 'Thiksay', 'Shey'],
  ['Leh Hqtr', 'Thiksay', 'Thiksey'],
  ['Nubra', 'Turtuk', 'Bogdang'],
  ['Nubra', 'Turtuk', 'Chulungkha'],
  ['Nubra', 'Turtuk', 'Tyakshi'],
  ['Nubra', 'Turtuk', 'Thanga Chathang'],
  ['Nubra', 'Turtuk', 'Turtok'],
];

/** Official name → the spelling an existing village row already uses, so it is not duplicated. */
const ALIASES = { 'Nimo': 'Nimmoo', 'Hemishok Pachan': 'Hemis Shukpachan', 'Turtok': 'Turtuk' };

module.exports = { LEH_VILLAGES, ALIASES };
