'use strict';
/**
 * The 130 revenue villages of Kargil district, by sub-division and tehsil (stored as the
 * block), from the district administration's list. Synced into the villages table on
 * every start, like the Leh list. Choskore appears twice: once in Kargil tehsil, once in Taisuru.
 */

const KARGIL_VILLAGES = [
  ['Drass', 'Drass', 'Matayeen'],
  ['Drass', 'Drass', 'Pandrass'],
  ['Drass', 'Drass', 'Trongion'],
  ['Drass', 'Drass', 'Youlboo'],
  ['Drass', 'Drass', 'Haripora (uninhabited)'],
  ['Drass', 'Drass', 'Drass'],
  ['Drass', 'Drass', 'Batokol (uninhabited)'],
  ['Drass', 'Drass', 'Mushkoo'],
  ['Drass', 'Drass', 'Holiyal'],
  ['Drass', 'Drass', 'Muradbagh'],
  ['Drass', 'Drass', 'Goshan'],
  ['Drass', 'Drass', 'Gindiyal'],
  ['Drass', 'Drass', 'Bhimbat'],
  ['Drass', 'Drass', 'Throungos'],
  ['Drass', 'Drass', 'Chowkiyal'],
  ['Drass', 'Drass', 'Jasgound'],
  ['Drass', 'Drass', 'Thasgam'],
  ['Drass', 'Drass', 'Shimsha'],
  ['Drass', 'Drass', 'Kharboo'],
  ['Kargil HQ', 'Kargil', 'Kaksar'],
  ['Kargil HQ', 'Kargil', 'Karkit'],
  ['Kargil HQ', 'Kargil', 'Drelong (Latoo)'],
  ['Kargil HQ', 'Kargil', 'Chuliskamboo'],
  ['Kargil HQ', 'Kargil', 'Hardass'],
  ['Kargil HQ', 'Kargil', 'Shilikchey'],
  ['Kargil HQ', 'Kargil', 'Poyen'],
  ['Kargil HQ', 'Kargil', 'Bagh Khumani'],
  ['Kargil HQ', 'Kargil', 'Kargil'],
  ['Kargil HQ', 'Kargil', 'Baroo'],
  ['Kargil HQ', 'Kargil', 'Minjee'],
  ['Kargil HQ', 'Kargil', 'Choskore'],
  ['Kargil HQ', 'Kargil', 'Safi'],
  ['Kargil HQ', 'Kargil', 'Batambis'],
  ['Kargil HQ', 'Kargil', 'Yourbaltak'],
  ['Kargil HQ', 'Kargil', 'Akchamal'],
  ['Kargil HQ', 'Kargil', 'Apatee'],
  ['Kargil HQ', 'Kargil', 'Tumail'],
  ['Kargil HQ', 'Kargil', 'Barchey'],
  ['Kargil HQ', 'Kargil', 'Pashkum'],
  ['Kargil HQ', 'Kargil', 'Silmoo'],
  ['Kargil HQ', 'Kargil', 'Lalung'],
  ['Kargil HQ', 'Kargil', 'Chulichan'],
  ['Kargil HQ', 'Kargil', 'Garkone'],
  ['Kargil HQ', 'Kargil', 'Darchiks'],
  ['Shargole', 'Shargole', 'Lotsum'],
  ['Shargole', 'Shargole', 'Darket'],
  ['Shargole', 'Shargole', 'Tacha'],
  ['Shargole', 'Shargole', 'Karit'],
  ['Shargole', 'Shargole', 'Numunchey'],
  ['Shargole', 'Shargole', 'Kukstay'],
  ['Shargole', 'Shargole', 'Skamboo'],
  ['Shargole', 'Shargole', 'Shargole'],
  ['Shargole', 'Shargole', 'Khachey'],
  ['Shargole', 'Shargole', 'Karamba'],
  ['Shargole', 'Shargole', 'Phoo'],
  ['Shargole', 'Shargole', 'Tingdoo'],
  ['Shargole', 'Shargole', 'Wakha'],
  ['Shargole', 'Shargole', 'Mulbekh'],
  ['Shakar-Chiktan', 'Shakar-Chiktan', 'Haniskote'],
  ['Shakar-Chiktan', 'Shakar-Chiktan', 'Bodhkharboo'],
  ['Shakar-Chiktan', 'Shakar-Chiktan', 'Stakchey'],
  ['Shakar-Chiktan', 'Shakar-Chiktan', 'Samrah'],
  ['Shakar-Chiktan', 'Shakar-Chiktan', 'Chiktan'],
  ['Shakar-Chiktan', 'Shakar-Chiktan', 'Kukshow'],
  ['Shakar-Chiktan', 'Shakar-Chiktan', 'Hagnis'],
  ['Shakar-Chiktan', 'Shakar-Chiktan', 'Sanjak'],
  ['Shakar-Chiktan', 'Shakar-Chiktan', 'Shakar'],
  ['Shakar-Chiktan', 'Shakar-Chiktan', 'Lamsoo Sandoo'],
  ['Shakar-Chiktan', 'Shakar-Chiktan', 'Youkma-Kharboo'],
  ['Sankoo', 'Sankoo', 'Trespone'],
  ['Sankoo', 'Sankoo', 'Kanoor'],
  ['Sankoo', 'Sankoo', 'Saliskote'],
  ['Sankoo', 'Sankoo', 'G.M.Pore'],
  ['Sankoo', 'Sankoo', 'Tambis'],
  ['Sankoo', 'Sankoo', 'Faroona'],
  ['Sankoo', 'Sankoo', 'Lankarchey'],
  ['Sankoo', 'Sankoo', 'Stakpa'],
  ['Sankoo', 'Sankoo', 'Umba'],
  ['Sankoo', 'Sankoo', 'Thangdumbur'],
  ['Sankoo', 'Sankoo', 'Nagmakusar'],
  ['Sankoo', 'Sankoo', 'Sangrah'],
  ['Sankoo', 'Sankoo', 'Karpokhar'],
  ['Sankoo', 'Sankoo', 'Barsoo'],
  ['Sankoo', 'Sankoo', 'Khandi'],
  ['Sankoo', 'Sankoo', 'Bartoo'],
  ['Sankoo', 'Sankoo', 'Shargandi'],
  ['Sankoo', 'Sankoo', 'Itcho'],
  ['Sankoo', 'Sankoo', 'Thasgam Thuina'],
  ['Sankoo', 'Sankoo', 'Karchey Khar'],
  ['Sankoo', 'Taisuru', 'Gialing'],
  ['Sankoo', 'Taisuru', 'Purtikchey'],
  ['Sankoo', 'Taisuru', 'Youljok'],
  ['Sankoo', 'Taisuru', 'Kargee'],
  ['Sankoo', 'Taisuru', 'Panikhar'],
  ['Sankoo', 'Taisuru', 'Printee'],
  ['Sankoo', 'Taisuru', 'Choskore'],
  ['Sankoo', 'Taisuru', 'Taisuru'],
  ['Sankoo', 'Taisuru', 'Khawos'],
  ['Sankoo', 'Taisuru', 'Namsuru'],
  ['Sankoo', 'Taisuru', 'Thulus Pursa'],
  ['Sankoo', 'Taisuru', 'Khochik'],
  ['Sankoo', 'Taisuru', 'Rangdom'],
  ['Sankoo', 'Taisuru', 'Parkachik'],
  ['Sankoo', 'Taisuru', 'Tangole'],
  ['Sankoo', 'Taisuru', 'Achambore'],
  ['Zanskar', 'Zanskar', 'Aksho'],
  ['Zanskar', 'Zanskar', 'Abran'],
  ['Zanskar', 'Zanskar', 'Hemiling'],
  ['Zanskar', 'Zanskar', 'Ramilskyagam'],
  ['Zanskar', 'Zanskar', 'Phay'],
  ['Zanskar', 'Zanskar', 'Ating'],
  ['Zanskar', 'Zanskar', 'Rantaksha'],
  ['Zanskar', 'Zanskar', 'Tungri'],
  ['Zanskar', 'Zanskar', 'Techakhasar'],
  ['Zanskar', 'Zanskar', 'Langmi Riging'],
  ['Zanskar', 'Zanskar', 'Karsha'],
  ['Zanskar', 'Zanskar', 'Padum'],
  ['Zanskar', 'Zanskar', 'Thungday Khumi'],
  ['Zanskar', 'Zanskar', 'Uptipipiting'],
  ['Zanskar', 'Zanskar', 'Rukruk'],
  ['Zanskar', 'Zanskar', 'Salapi Gyapak'],
  ['Zanskar', 'Zanskar', 'Sani'],
  ['Zanskar', 'Zanskar', 'Zangla'],
  ['Zanskar', 'Zanskar', 'Pipcha'],
  ['Zanskar', 'Zanskar', 'Raru Money'],
  ['Zanskar', 'Zanskar', 'Icher'],
  ['Zanskar', 'Zanskar', 'Chah'],
  ['Zanskar', 'Zanskar', 'Testa'],
  ['Zanskar', 'Zanskar', 'Kargyak'],
  ['Zanskar', 'Zanskar', 'Shunshday'],
];

module.exports = { KARGIL_VILLAGES };
