'use strict';
/**
 * Districts of Ladakh and their revenue villages, as redefined by the Ladakh Gazette
 * notification S.O. 180 of 27 April 2026 (Revenue Department), which created Sham, Nubra,
 * Changthang, Zanskar and Drass alongside Leh and Kargil.
 *
 * The notification only moves villages between districts: sub-divisions, tehsils/blocks
 * and patwar halqas stay as they were until notified separately, so each village keeps
 * its existing block and sub-division here.
 *
 * Each row is [sub-division, block, name, gazette spelling]. The name is the one already
 * used in the app (from the district village lists); the gazette spelling is kept only
 * when it differs, so a search for either finds the village.
 *
 * Synced into the villages table on every start (syncOfficialVillages in db.js).
 */

const DISTRICTS = [
  { id: 'leh', name: 'Leh', hq: 'Leh' },
  { id: 'sham', name: 'Sham', hq: 'Khaltse' },
  { id: 'nubra', name: 'Nubra', hq: 'Diskit' },
  { id: 'changthang', name: 'Changthang', hq: 'Nyoma' },
  { id: 'kargil', name: 'Kargil', hq: 'Kargil' },
  { id: 'zanskar', name: 'Zanskar', hq: 'Padum' },
  { id: 'drass', name: 'Drass', hq: 'Drass-Ranbirpura' },
];

const VILLAGES = {
  // Leh — 44 villages
  leh: [
    ['Leh Hqtr', 'Leh', 'Gompa Gangless'],
    ['Leh Hqtr', 'Leh', 'Sankar Yourtung'],
    ['Leh Hqtr', 'Leh', 'Leh Ladakh'],
    ['Leh Hqtr', 'Leh', 'Skara'],
    ['Leh Hqtr', 'Leh', 'Cholglamsar', 'Choglamsar'],
    ['Leh Hqtr', 'Leh', 'Saboo'],
    ['Leh Hqtr', 'Thiksay', 'Thiksey', 'Thiksay'],
    ['Leh Hqtr', 'Thiksay', 'Nang'],
    ['Leh Hqtr', 'Thiksay', 'Rambir Por', 'Rambirpur'],
    ['Leh Hqtr', 'Thiksay', 'Shey', 'Shay'],
    ['Leh Hqtr', 'Leh', 'Phyang'],
    ['Leh Hqtr', 'Leh', 'Spituk'],
    ['Leh Hqtr', 'Leh', 'Phey', 'Phay'],
    ['Likir', 'Nimoo', 'Taroo', 'Taru'],
    ['Likir', 'Nimoo', 'Umla'],
    ['Likir', 'Nimoo', 'Skiumarkha', 'Sku Marka'],
    ['Likir', 'Nimoo', 'Rumbak'],
    ['Likir', 'Nimoo', 'Chiling Sumda', 'Chilling Sumda'],
    ['Khaltsi', 'Singaylalok', 'Lingshet', 'Lingshed'],
    ['Khaltsi', 'Singaylalok', 'Youl Chung', 'Youlchung'],
    ['Likir', 'Nimoo', 'Bazgoo', 'Basgo'],
    ['Likir', 'Nimoo', 'Ney'],
    ['Likir', 'Nimoo', 'Nimmoo', 'Nimoo'],
    ['Leh Hqtr', 'Chuchot', 'Mathoo', 'Matho'],
    ['Leh Hqtr', 'Chuchot', 'Stakna', 'Stanka'],
    ['Leh Hqtr', 'Chuchot', 'Chuchot Yakma', 'Chushot Yokma'],
    ['Leh Hqtr', 'Chuchot', 'Stok'],
    ['Leh Hqtr', 'Chuchot', 'Chuchot Gongma', 'Chushot Gongma'],
    ['Leh Hqtr', 'Chuchot', 'Chuchot Shama', 'Chushot Shamma'],
    ['Kharu', 'Kharu', 'Igoo'],
    ['Kharu', 'Kharu', 'Langokor', 'Langkor'],
    ['Kharu', 'Kharu', 'Shara'],
    ['Kharu', 'Kharu', 'Sharnose', 'Sharnos'],
    ['Kharu', 'Kharu', 'Phuktse', 'Phuktsay'],
    ['Kharu', 'Kharu', 'Sakti'],
    ['Kharu', 'Kharu', 'Kharu'],
    ['Kharu', 'Kharu', 'Chemday'],
    ['Kharu', 'Kharu', 'Matselang', 'Martselang'],
    ['Kharu', 'Kharu', 'Hemis'],
    ['Kharu', 'Kharu', 'Shang'],
    ['Kharu', 'Kharu', 'Changa'],
    ['Kharu', 'Kharu', 'Upshi'],
    ['Kharu', 'Kharu', 'Miru', 'Meru'],
    ['Kharu', 'Kharu', 'Gia'],
  ],
  // Sham — 27 villages
  sham: [
    ['Khaltsi', 'Khaltsi', 'Khaltsi'],
    ['Khaltsi', 'Khaltsi', 'Skindiang', 'Skindiyang'],
    ['Khaltsi', 'Singaylalok', 'Fotoksar'],
    ['Khaltsi', 'Singaylalok', 'Wanla'],
    ['Khaltsi', 'Khaltsi', 'Lamayuru'],
    ['Khaltsi', 'Khaltsi', 'Kanji', 'Kanjee'],
    ['Shakar-Chiktan', 'Shakar-Chiktan', 'Bodhkharboo'],
    ['Shakar-Chiktan', 'Shakar-Chiktan', 'Haniskote'],
    ['Khaltsi', 'Skurbuchan', 'Skur Buchan', 'Skurbuchan'],
    ['Khaltsi', 'Khaltsi', 'Leh Dho', 'Lehdo'],
    ['Shakar-Chiktan', 'Shakar-Chiktan', 'Kukshow'],
    ['Khaltsi', 'Skurbuchan', 'Damkhar', 'Domkhar'],
    ['Khaltsi', 'Khaltsi', 'Takmachik'],
    ['Khaltsi', 'Skurbuchan', 'Dah', 'Dha Bema'],
    ['Khaltsi', 'Skurbuchan', 'Hanoo', 'Hanu'],
    ['Kargil HQ', 'Kargil', 'Garkone'],
    ['Kargil HQ', 'Kargil', 'Darchiks'],
    ['Likir', 'Nimoo', 'Likir'],
    ['Likir', 'Saspol', 'Suspol', 'Saspol'],
    ['Likir', 'Saspol', 'Hemis Shukpachan', 'Hemisshukpachan'],
    ['Likir', 'Saspol', 'Saspochey', 'Saspochay'],
    ['Likir', 'Saspol', 'Alchi'],
    ['Likir', 'Saspol', 'Giramangu', 'Gaira-Magnu'],
    ['Khaltsi', 'Khaltsi', 'Temisgam'],
    ['Khaltsi', 'Khaltsi', 'Tia'],
    ['Khaltsi', 'Khaltsi', 'Nurla'],
    ['Likir', 'Saspol', 'Tarhipti', 'Tar Hipti'],
  ],
  // Nubra — 30 villages
  nubra: [
    ['Nubra', 'Diskit', 'Disket', 'Diskit'],
    ['Nubra', 'Diskit', 'Hundar', 'Hunder'],
    ['Nubra', 'Diskit', 'Skanpuk', 'Skampuk'],
    ['Nubra', 'Diskit', 'Hundar Dok', 'Hunder Dok'],
    ['Nubra', 'Diskit', 'Partapur', 'Partapuk'],
    ['Nubra', 'Diskit', 'Khardong'],
    ['Nubra', 'Diskit', 'Khalsar', 'Khaltsar'],
    ['Nubra', 'Diskit', 'Tangyar'],
    ['Nubra', 'Diskit', 'Diger', 'Digger'],
    ['Nubra', 'Diskit', 'Khema Khungru', 'KhamaKhungru'],
    ['Nubra', 'Diskit', 'Udmaru', 'Udamru'],
    ['Nubra', 'Diskit', 'Skuru'],
    ['Nubra', 'Diskit', 'Terchey', 'Tartse'],
    ['Nubra', 'Diskit', 'Hundri'],
    ['Nubra', 'Diskit', 'Largiab', 'Largyab'],
    ['Nubra', 'Diskit', 'Warisfistan', 'VarisFastan'],
    ['Nubra', 'Turtuk', 'Bogdang'],
    ['Nubra', 'Turtuk', 'Chulungkha'],
    ['Nubra', 'Turtuk', 'Turtuk Yul'],
    ['Nubra', 'Turtuk', 'Turtuk Farol'],
    ['Nubra', 'Turtuk', 'Tyakshi-A'],
    ['Nubra', 'Turtuk', 'Tyakshi-B'],
    ['Nubra', 'Turtuk', 'Thanga Chathang', 'Thang'],
    ['Nubra', 'Panamik', 'Sumoor'],
    ['Nubra', 'Panamik', 'Tiggar', 'Tigger'],
    ['Nubra', 'Diskit', 'Lakjung'],
    ['Nubra', 'Panamik', 'Chamshan Charasa', 'ChamshaCharasa'],
    ['Nubra', 'Panamik', 'Panamic', 'Panamik'],
    ['Nubra', 'Panamik', 'Kubed'],
    ['Nubra', 'Panamik', 'Khemi', 'Kheme'],
  ],
  // Changthang — 24 villages
  changthang: [
    ['Nyoma', 'Nyoma', 'Nyoma'],
    ['Nyoma', 'Nyoma', 'Mood', 'Mudh'],
    ['Nyoma', 'Nyoma', 'Anlay'],
    ['Nyoma', 'Nyoma', 'Koyul'],
    ['Nyoma', 'Nyoma', 'Demjok', 'Damjok'],
    ['Nyoma', 'Rong-Chumathang', 'Kumgyam', 'Kungaym'],
    ['Nyoma', 'Rong-Chumathang', 'Kerey', 'Kariy'],
    ['Nyoma', 'Rong-Chumathang', 'Skitmang'],
    ['Nyoma', 'Rong-Chumathang', 'Chumathang'],
    ['Nyoma', 'Rong-Chumathang', 'Himya', 'Hemya'],
    ['Nyoma', 'Rong-Chumathang', 'Teri'],
    ['Nyoma', 'Rong-Chumathang', 'Tarchit'],
    ['Nyoma', 'Rong-Chumathang', 'Tukla'],
    ['Nyoma', 'Rong-Chumathang', 'Liktse'],
    ['Nyoma', 'Rupsho-Puga', 'Karzok', 'Korzok'],
    ['Nyoma', 'Rupsho-Puga', 'Samad Rakchan', 'Samadrokchan'],
    ['Nyoma', 'Rupsho-Puga', 'Kharnak'],
    ['Durbuk', 'Durbuk', 'Durbuk'],
    ['Durbuk', 'Durbuk', 'Tangste', 'Tangtse'],
    ['Durbuk', 'Durbuk', 'Shachukul'],
    ['Durbuk', 'Durbuk', 'Phulaks'],
    ['Durbuk', 'Durbuk', 'Chushul'],
    ['Durbuk', 'Durbuk', 'Man Pangong', 'Maan Pangong'],
    ['Durbuk', 'Durbuk', 'Kargyam'],
  ],
  // Kargil — 80 villages (80 in the notification, plus Sankoo)
  kargil: [
    ['Kargil HQ', 'Kargil', 'Kaksar'],
    ['Kargil HQ', 'Kargil', 'Karkit'],
    ['Kargil HQ', 'Kargil', 'Drelong (Latoo)'],
    ['Kargil HQ', 'Kargil', 'Chuliskamboo'],
    ['Kargil HQ', 'Kargil', 'Hardass'],
    ['Kargil HQ', 'Kargil', 'Shilikchey'],
    ['Kargil HQ', 'Kargil', 'Poyen'],
    ['Kargil HQ', 'Kargil', 'Bagh Khumani'],
    ['Kargil HQ', 'Kargil', 'Kargil'],
    ['Kargil HQ', 'Kargil', 'Baroo'],
    ['Kargil HQ', 'Kargil', 'Minjee'],
    ['Kargil HQ', 'Kargil', 'Choskore'],
    ['Kargil HQ', 'Kargil', 'Safi'],
    ['Kargil HQ', 'Kargil', 'Batambis'],
    ['Kargil HQ', 'Kargil', 'Yourbaltak'],
    ['Kargil HQ', 'Kargil', 'Akchamal'],
    ['Kargil HQ', 'Kargil', 'Apatee'],
    ['Kargil HQ', 'Kargil', 'Tumail'],
    ['Kargil HQ', 'Kargil', 'Barchey'],
    ['Kargil HQ', 'Kargil', 'Silmoo'],
    ['Kargil HQ', 'Kargil', 'Lalung'],
    ['Kargil HQ', 'Kargil', 'Chulichan'],
    ['Kargil HQ', 'Kargil', 'Pashkum'],
    ['Shargole', 'Shargole', 'Lotsum', 'Lochum'],
    ['Shargole', 'Shargole', 'Darket'],
    ['Shargole', 'Shargole', 'Tacha'],
    ['Shargole', 'Shargole', 'Karit'],
    ['Shargole', 'Shargole', 'Numunchey'],
    ['Shargole', 'Shargole', 'Kukstay'],
    ['Shargole', 'Shargole', 'Skamboo'],
    ['Shargole', 'Shargole', 'Shargole', 'Shergole'],
    ['Shargole', 'Shargole', 'Khachey'],
    ['Shargole', 'Shargole', 'Karamba'],
    ['Shargole', 'Shargole', 'Phoo'],
    ['Shargole', 'Shargole', 'Tingdoo'],
    ['Shargole', 'Shargole', 'Wakha'],
    ['Shargole', 'Shargole', 'Mulbekh'],
    ['Shakar-Chiktan', 'Shakar-Chiktan', 'Stakchey'],
    ['Shakar-Chiktan', 'Shakar-Chiktan', 'Samrah'],
    ['Shakar-Chiktan', 'Shakar-Chiktan', 'Chiktan'],
    ['Shakar-Chiktan', 'Shakar-Chiktan', 'Hagnis'],
    ['Shakar-Chiktan', 'Shakar-Chiktan', 'Sanjak'],
    ['Shakar-Chiktan', 'Shakar-Chiktan', 'Shakar'],
    ['Shakar-Chiktan', 'Shakar-Chiktan', 'Lamsoo Sandoo'],
    ['Shakar-Chiktan', 'Shakar-Chiktan', 'Youkma-Kharboo', 'Youkma Kharboo'],
    ['Sankoo', 'Sankoo', 'Trespone'],
    ['Sankoo', 'Sankoo', 'Kanoor'],
    ['Sankoo', 'Sankoo', 'Saliskote'],
    ['Sankoo', 'Sankoo', 'G.M.Pore', 'Gound Mangal Pore'],
    ['Sankoo', 'Sankoo', 'Tambis'],
    ['Sankoo', 'Sankoo', 'Faroona'],
    ['Sankoo', 'Sankoo', 'Lankarchey'],
    ['Sankoo', 'Sankoo', 'Stakpa'],
    ['Sankoo', 'Sankoo', 'Umba'],
    ['Sankoo', 'Sankoo', 'Thangdumbur'],
    ['Sankoo', 'Sankoo', 'Nagmakusar'],
    ['Sankoo', 'Sankoo', 'Sangrah'],
    ['Sankoo', 'Sankoo', 'Karpokhar'],
    ['Sankoo', 'Sankoo', 'Barsoo'],
    ['Sankoo', 'Sankoo', 'Khandi'],
    ['Sankoo', 'Sankoo', 'Bartoo'],
    ['Sankoo', 'Sankoo', 'Shargandi'],
    ['Sankoo', 'Sankoo', 'Itcho'],
    ['Sankoo', 'Sankoo', 'Thasgam Thuina'],
    ['Sankoo', 'Sankoo', 'Karchey Khar'],
    ['Sankoo', 'Taisuru', 'Gialing', 'Gailing'],
    ['Sankoo', 'Taisuru', 'Purtikchey'],
    ['Sankoo', 'Taisuru', 'Youljok', 'Youljuk'],
    ['Sankoo', 'Taisuru', 'Kargee'],
    ['Sankoo', 'Taisuru', 'Panikhar'],
    ['Sankoo', 'Taisuru', 'Printee'],
    ['Sankoo', 'Taisuru', 'Choskore'],
    ['Sankoo', 'Taisuru', 'Taisuru'],
    ['Sankoo', 'Taisuru', 'Khawos'],
    ['Sankoo', 'Taisuru', 'Namsuru'],
    ['Sankoo', 'Taisuru', 'Thulus Pursa'],
    ['Sankoo', 'Taisuru', 'Khochik'],
    ['Sankoo', 'Taisuru', 'Parkachik'],
    ['Sankoo', 'Taisuru', 'Tangole'],
    ['Sankoo', 'Taisuru', 'Achambore'],
    ['Sankoo', 'Sankoo', 'Sankoo'],   // a village in its own right, though not on the revenue list
  ],
  // Zanskar — 26 villages
  zanskar: [
    ['Zanskar', 'Zanskar', 'Padum'],
    ['Zanskar', 'Zanskar', 'Sani'],
    ['Zanskar', 'Zanskar', 'Uptipipiting'],
    ['Zanskar', 'Zanskar', 'Rukruk', 'Ruk-Ruk'],
    ['Zanskar', 'Zanskar', 'Salapi Gyapak'],
    ['Zanskar', 'Zanskar', 'Karsha'],
    ['Zanskar', 'Zanskar', 'Techakhasar'],
    ['Zanskar', 'Zanskar', 'Langmi Riging'],
    ['Zanskar', 'Zanskar', 'Phay'],
    ['Zanskar', 'Zanskar', 'Ramilskyagam'],
    ['Zanskar', 'Zanskar', 'Hemiling'],
    ['Zanskar', 'Zanskar', 'Rantaksha'],
    ['Zanskar', 'Zanskar', 'Tungri'],
    ['Zanskar', 'Zanskar', 'Ating'],
    ['Zanskar', 'Zanskar', 'Abran'],
    ['Zanskar', 'Zanskar', 'Aksho'],
    ['Sankoo', 'Taisuru', 'Rangdom'],
    ['Zanskar', 'Zanskar', 'Zangla'],
    ['Zanskar', 'Zanskar', 'Thungday Khumi'],
    ['Zanskar', 'Zanskar', 'Chah'],
    ['Zanskar', 'Zanskar', 'Testa'],
    ['Zanskar', 'Zanskar', 'Kargyak'],
    ['Zanskar', 'Zanskar', 'Shunshday'],
    ['Zanskar', 'Zanskar', 'Icher'],
    ['Zanskar', 'Zanskar', 'Pipcha'],
    ['Zanskar', 'Zanskar', 'Raru Money', 'Rarumoney'],
  ],
  // Drass — 19 villages
  drass: [
    ['Drass', 'Drass', 'Drass'],
    ['Drass', 'Drass', 'Trongion'],
    ['Drass', 'Drass', 'Haripora (uninhabited)'],
    ['Drass', 'Drass', 'Goshan'],
    ['Drass', 'Drass', 'Muradbagh'],
    ['Drass', 'Drass', 'Youlboo'],
    ['Drass', 'Drass', 'Gindiyal'],
    ['Drass', 'Drass', 'Bhimbat'],
    ['Drass', 'Drass', 'Throungos'],
    ['Drass', 'Drass', 'Chowkiyal'],
    ['Drass', 'Drass', 'Batokol (uninhabited)'],
    ['Drass', 'Drass', 'Holiyal'],
    ['Drass', 'Drass', 'Mushkoo'],
    ['Drass', 'Drass', 'Matayeen'],
    ['Drass', 'Drass', 'Pandrass'],
    ['Drass', 'Drass', 'Thasgam'],
    ['Drass', 'Drass', 'Jasgound'],
    ['Drass', 'Drass', 'Kharboo'],
    ['Drass', 'Drass', 'Shimsha'],
  ],
};

/**
 * Names a village had in an earlier list. The notification splits Turtuk and Tyakshi in
 * two; the existing village (and any surveys in it) carries on as the first half.
 */
const FORMER_NAMES = {
  'Turtuk Yul': ['Turtuk', 'Turtok'],
  'Tyakshi-A': ['Tyakshi'],
};

module.exports = { DISTRICTS, VILLAGES, FORMER_NAMES };
